# Generated by Django 4.0.1 on 2022-01-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField()),
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('source', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
